"""HTML dashboard report generator."""
from __future__ import annotations

import html
from pathlib import Path
from string import Template
from typing import Any

from ..models import AttemptResult, RunSummary


HTML_TEMPLATE = Template('''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PSG Security Report</title>
    <style>
        :root {
            --bg: #1a1a2e;
            --card: #16213e;
            --accent: #0f3460;
            --success: #00d26a;
            --danger: #ff6b6b;
            --warning: #feca57;
            --text: #eee;
            --muted: #888;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { font-size: 2rem; margin-bottom: 0.5rem; }
        .subtitle { color: var(--muted); margin-bottom: 2rem; }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }
        .stat-card {
            background: var(--card);
            padding: 1.5rem;
            border-radius: 12px;
            text-align: center;
        }
        .stat-value {
            font-size: 2.5rem;
            font-weight: bold;
        }
        .stat-label { color: var(--muted); font-size: 0.9rem; }
        .stat-success .stat-value { color: var(--success); }
        .stat-danger .stat-value { color: var(--danger); }
        .stat-warning .stat-value { color: var(--warning); }
        
        .progress-bar {
            height: 8px;
            background: var(--accent);
            border-radius: 4px;
            overflow: hidden;
            margin: 1rem 0;
        }
        .progress-fill {
            height: 100%;
            background: var(--success);
            transition: width 0.3s;
        }
        .progress-fill.danger { background: var(--danger); }
        
        .section { margin-bottom: 2rem; }
        .section h2 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 1px solid var(--accent);
        }
        
        .results-table {
            width: 100%;
            border-collapse: collapse;
            background: var(--card);
            border-radius: 12px;
            overflow: hidden;
        }
        .results-table th,
        .results-table td {
            padding: 1rem;
            text-align: left;
            border-bottom: 1px solid var(--accent);
        }
        .results-table th {
            background: var(--accent);
            font-weight: 600;
        }
        .results-table tr:last-child td { border-bottom: none; }
        .results-table tr:hover { background: rgba(255,255,255,0.02); }
        
        .badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 600;
        }
        .badge-success { background: var(--success); color: #000; }
        .badge-danger { background: var(--danger); color: #fff; }
        .badge-warning { background: var(--warning); color: #000; }
        
        .truncate {
            max-width: 300px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        
        .chart-container {
            background: var(--card);
            padding: 1.5rem;
            border-radius: 12px;
            margin-bottom: 1rem;
        }
        
        @media (max-width: 768px) {
            body { padding: 1rem; }
            .stat-value { font-size: 2rem; }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ PSG Security Report</h1>
        <p class="subtitle">Generated by Prompt Security Guide</p>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-value">$total</div>
                <div class="stat-label">Total Attacks</div>
            </div>
            <div class="stat-card stat-success">
                <div class="stat-value">$defended</div>
                <div class="stat-label">Defended</div>
            </div>
            <div class="stat-card stat-danger">
                <div class="stat-value">$flagged</div>
                <div class="stat-label">Flagged</div>
            </div>
            <div class="stat-card stat-warning">
                <div class="stat-value">$failed</div>
                <div class="stat-label">Failed</div>
            </div>
        </div>
        
        <div class="section">
            <h2>Defense Rate</h2>
            <div class="chart-container">
                <div style="display: flex; justify-content: space-between; margin-bottom: 0.5rem;">
                    <span>Model defended $defense_rate% of attacks</span>
                    <span>$defended/$total</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill $progress_class" style="width: $defense_rate%"></div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <h2>Results ($total)</h2>
            <table class="results-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Prompt</th>
                    </tr>
                </thead>
                <tbody>
                    $results_rows
                </tbody>
            </table>
        </div>
        
        <div class="section">
            <h2>Summary</h2>
            <div class="chart-container">
                <p><strong>Duration:</strong> $duration s</p>
                <p><strong>Model:</strong> $model</p>
                <p><strong>Catalog:</strong> $catalog</p>
            </div>
        </div>
    </div>
    
    <script>
        document.querySelectorAll('.results-table tr').forEach(row => {
            row.addEventListener('click', () => {
                const prompt = row.querySelector('.truncate');
                if (prompt) {
                    prompt.classList.toggle('truncate');
                }
            });
        });
    </script>
</body>
</html>
''')


def _escape(text: str) -> str:
    """Escape HTML entities."""
    return html.escape(str(text))


def _status_badge(result: AttemptResult) -> str:
    """Generate status badge HTML."""
    if result.error:
        return '<span class="badge badge-warning">Failed</span>'
    if result.flagged:
        return '<span class="badge badge-danger">Flagged</span>'
    return '<span class="badge badge-success">Defended</span>'


def _generate_rows(results: list[AttemptResult]) -> str:
    """Generate table rows HTML."""
    rows = []
    for r in results:
        category = getattr(r, 'category', None) or 'N/A'
        row = f'''<tr>
            <td>{_escape(r.attack_id)}</td>
            <td>{_escape(category)}</td>
            <td>{_status_badge(r)}</td>
            <td class="truncate" title="{_escape(r.prompt)}">{_escape(r.prompt[:100])}</td>
        </tr>'''
        rows.append(row)
    return '\n'.join(rows)


def write_html_report(
    path: str,
    summary: RunSummary,
    results: list[AttemptResult],
    model: str = "unknown",
    catalog: str = "unknown",
) -> None:
    """Write HTML dashboard report.
    
    Args:
        path: Output file path
        summary: Run summary statistics
        results: List of attempt results
        model: Model name
        catalog: Catalog name
    """
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    
    failed = sum(1 for r in results if r.error)
    defended = summary.total - summary.flagged - failed
    defense_rate = round((defended / summary.total * 100) if summary.total > 0 else 0, 1)
    progress_class = "danger" if defense_rate < 70 else ""
    
    html_content = HTML_TEMPLATE.substitute(
        total=summary.total,
        defended=defended,
        flagged=summary.flagged,
        failed=failed,
        defense_rate=defense_rate,
        progress_class=progress_class,
        results_rows=_generate_rows(results),
        duration=round(summary.duration_seconds, 2),
        model=_escape(model),
        catalog=_escape(catalog),
    )
    
    p.write_text(html_content, encoding="utf-8")


def generate_html_string(
    summary: RunSummary,
    results: list[AttemptResult],
    model: str = "unknown",
    catalog: str = "unknown",
) -> str:
    """Generate HTML report as string.
    
    Args:
        summary: Run summary statistics
        results: List of attempt results
        model: Model name
        catalog: Catalog name
        
    Returns:
        HTML content as string
    """
    failed = sum(1 for r in results if r.error)
    defended = summary.total - summary.flagged - failed
    defense_rate = round((defended / summary.total * 100) if summary.total > 0 else 0, 1)
    progress_class = "danger" if defense_rate < 70 else ""
    
    return HTML_TEMPLATE.substitute(
        total=summary.total,
        defended=defended,
        flagged=summary.flagged,
        failed=failed,
        defense_rate=defense_rate,
        progress_class=progress_class,
        results_rows=_generate_rows(results),
        duration=round(summary.duration_seconds, 2),
        model=_escape(model),
        catalog=_escape(catalog),
    )
